# CONFIGURACIÓN DE POSTGRESQL 18
spring.datasource.url=jdbc:postgresql://localhost:5432/zarpronix_db
spring.datasource.username=postgres
spring.datasource.password=Zarcor994

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# SERVIDOR Y SEGURIDAD
server.port=8080
# Permitir que el frontend acceda a las APIs si usas puertos diferentes
spring.mvc.cors.allowed-origins=*